### PR TITLE
Validate Application Cluster Names In shipperctl admin clusters apply

### LINKED ISSUE #61: clusters apply fails if context name has underscore
GKE clusters typically have underscore in them (ie.  `gke_ACCOUNT_ZONE_CLUSTERNAME`), and that causes the apply to fail

Workaround is to rename *contexts - context - name* in `~/.kube/config` 

```
shipperctl admin clusters apply -f
...
Joining management cluster gke_account_us-central1-a_somename to application cluster gke_account_us-central1-a_somename:
Creating or updating the cluster object for cluster gke_account_us-central1-a_somename on the management cluster... Error! Cluster.shipper.booking.com "gke_account_us-central1-a_somename" is invalid: metadata.name: Invalid value: "gke_account_us-central1-a_somename": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

### PR DESCRIPTION
**Pull request by parhamdoustdar**
This pull request does the following:

- Moves the validation of the application cluster to the very beginning so that we don't leave the clusters in a half-state
- Validates the application cluster name to make sure that it's a valid object name. The reason this is not done for the management cluster is that the management cluster is not turned into a Cluster object.

Fixes #61.

### CODE REVIEW

File: cmd/shipperctl/cmd/apply.go [hunk 1]
```diff
@@ -94,6 +99,20 @@ func runApplyClustersCommand(cmd *cobra.Command, args []string) error {
 	return nil
 }
 
+func validateConfiguration(configuration *config.ClustersConfiguration) error {
+	for _, cluster := range configuration.ApplicationClusters {
+		if msgs := validation.IsDNS1123Subdomain(cluster.Name); len(msgs) > 0 {
+			return fmt.Errorf("\"%s\" is not a valid cluster name in Kubernetes. If this is the name of a context in your Kubernetes configuration, check out the relevant example at https://docs.shipper-k8s.io/en/latest/operations/shipperctl.html#using-contexts-that-are-not-valid-as-a-kubernetes-name", cluster.Name)
```
Comment (icanhazbroccoli) [inline cmd/shipperctl/cmd/apply.go]: Consider replacing \"%s\" with %q

File: cmd/shipperctl/cmd/apply.go [hunk 2]
```diff
@@ -94,6 +99,20 @@ func runApplyClustersCommand(cmd *cobra.Command, args []string) error {
 	return nil
 }
 
+func validateConfiguration(configuration *config.ClustersConfiguration) error {
```
Comment (icanhazbroccoli) [inline cmd/shipperctl/cmd/apply.go]: Consider a method name reflecting cluster-bounded scope of the operation, e.g.: `validateClusterConfiguration`

File: docs/operations/shipperctl.rst [hunk 3]
```diff
@@ -78,6 +84,9 @@ Here is something more interesting: having 2 application clusters, and marking o
     scheduler:
       unschedulable: true
 
+Using Contexts That Are Not Valid As a Kubernetes Name
```
Comment (icanhazbroccoli) [inline docs/operations/shipperctl.rst]: Consider renaming this title: personally, I found it quite confusing. Example: Workaround for GKE cluster naming convention conflict.
