### PR TITLE
Fixed runtime panic in clusterclientstore fixes #293

### LINKED ISSUE #293: Runtime panic caused by a no-checksum annotation on a secret object
While creating a new cluster, we missed the checksum annotation in it's secret and this caused a runtime panic:

```
E0305 15:47:10.209222       1 runtime.go:71] Observed a panic: Secret "foo-bar-baz" doesn't have a checksum annotation. this should be checked before calling 'create'
goroutine 501 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1356f40, 0xc0a3081be0)
	/shipper/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/shipper/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51 +0x82
panic(0x1356f40, 0xc0a3081be0)
	/usr/lib64/go/src/runtime/panic.go:679 +0x1b2
github.com/bookingcom/shipper/pkg/clusterclientstore.(*Store).create(0xc0001c0280, 0xc0e7260000, 0xc1423de3c0, 0xc1423de3c0, 0x0)
	/shipper/pkg/clusterclientstore/store.go:263 +0x7b2
github.com/bookingcom/shipper/pkg/clusterclientstore.(*Store).syncCluster(0xc0001c0280, 0xc12c394360, 0x22, 0xc12be33a10, 0xc0007be800)
	/shipper/pkg/clusterclientstore/store.go:195 +0x7ac
github.com/bookingcom/shipper/pkg/clusterclientstore.processNextWorkItem(0x17ca520, 0xc0002302e0, 0xc00116ee38, 0x0)
	/shipper/pkg/clusterclientstore/queue.go:118 +0x112
github.com/bookingcom/shipper/pkg/clusterclientstore.(*Store).clusterWorker(0xc0001c0280)
	/shipper/pkg/clusterclientstore/queue.go:17 +0x5d
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00091e3c0)
	/shipper/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00091e3c0, 0x3b9aca00, 0x0, 0x1, 0xc0001d0000)
	/shipper/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00091e3c0, 0x3b9aca00, 0xc0001d0000)



	/shipper/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/bookingcom/shipper/pkg/clusterclientstore.(*Store).Run
	/shipper/pkg/clusterclientstore/store.go:103 +0x3de
panic: Secret "foo-bar-baz" doesn't have a checksum annotation. this should be checked before calling 'create' [recovered]
	panic: Secret "foo-bar-baz" doesn't have a checksum annotation. this should be checked before calling 'create'

goroutine 501 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/shipper/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x1356f40, 0xc0a3081be0)
	/usr/lib64/go/src/runtime/panic.go:679 +0x1b2
github.com/bookingcom/shipper/pkg/clusterclientstore.(*Store).create(0xc0001c0280, 0xc0e7260000, 0xc1423de3c0, 0xc1423de3c0, 0x0)
	/shipper/pkg/clusterclientstore/store.go:263 +0x7b2
github.com/bookingcom/shipper/pkg/clusterclientstore.(*Store).syncCluster(0xc0001c0280, 0xc12c394360, 0x22, 0xc12be33a10, 0xc0007be800)
	/shipper/pkg/clusterclientstore/store.go:195 +0x7ac
github.com/bookingcom/shipper/pkg/clusterclientstore.processNextWorkItem(0x17ca520, 0xc0002302e0, 0xc00116ee38, 0x0)
	/shipper/pkg/clusterclientstore/queue.go:118 +0x112
github.com/bookingcom/shipper/pkg/clusterclientstore.(*Store).clusterWorker(0xc0001c0280)
	/shipper/pkg/clusterclientstore/queue.go:17 +0x5d
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00091e3c0)
	/shipper/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00091e3c0, 0x3b9aca00, 0x0, 0x1, 0xc0001d0000)
	/shipper/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00091e3c0, 0x3b9aca00, 0xc0001d0000)
	/shipper/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/bookingcom/shipper/pkg/clusterclientstore.(*Store).Run
	/shipper/pkg/clusterclientstore/store.go:103 +0x3de
rpc error: code = Unknown desc = Error: No such container: c5181c73e5a8181e8fa5a11f81b8b04cab55732766a71176aec6f4bcbbe41405
```

### PR DESCRIPTION
**Pull request by icanhazbroccoli**
**Part1**: This commit addresses a runtime panic we observed in our production
environment while provisioning a new cluster. The new cluster was
provisioned manually (not using shipperctl) and it's corresponding
secret object was missing a checksum annotation. Whereas it's a runtime
error, it makes Shipper to be quite vulnerable to this kind of
amendments and this commit alters panicing with an unrecoverable error
returned by syncSecret/1 routine.

**Part2**: Removed SecretChecksumAnnotation from cluster secret annotations
    
This commit removes SecretChecksumAnnotation annotation. In the current
implementation this annotation is a must-have item that ensures that the
cluster was provisioned correctly and notifies clusterclientstore on
secret changes.

In this commit we remove this annotation and re-compute cluster secret
checksum every time syncSecret/1 is being invoked. This approach ensures
no preliminary config is needed to get a cluster object to an operating
state. Every time a cluster secret changes, the cache invalidates the
stored cluster object and re-creates it.
    

Signed-off-by: Oleg Sidorov <oleg.sidorov@booking.com>

### CODE REVIEW

File: pkg/clusterclientstore/store.go [hunk 1]
```diff
@@ -303,13 +300,15 @@ func (s *Store) syncSecret(key string) error {
...
-	if !ok {
-		panic(fmt.Sprintf("Secret %q doesn't have a checksum annotation. this should be checked before calling 'create'", secret.Name))
-	}
+func computeSecretChecksum(secret *corev1.Secret) string {
+	hash := crc32.NewIEEE()
+	hash.Write(secret.Data["ca.crt"])
+	hash.Write(secret.Data["token"])
+	sum := hex.EncodeToString(hash.Sum(nil))
+	return sum
+}
```
Comment (juliogreff) [inline pkg/clusterclientstore/store.go]: I wonder if we shouldn't compute the checksum of all of the secret's Data instead of just a few cherry-picked keys. And, if we do decide to just cherry-pick keys, maybe we should pick all of the possible ones Shipper uses to generate clients: https://github.com/bookingcom/shipper/blob/jgreff/app-targets/pkg/client/client.go#L40-L83

Comment (icanhazbroccoli) [reply pkg/clusterclientstore/store.go]: @juliogreff good point, thanks. Spreading this logic of cherry-picking fragments of secrets seemed quite impractical to me, therefore it hashes the entire Data dataset now: https://github.com/bookingcom/shipper/pull/294/files#diff-dc16ca8ff134c0aed1343a896c6f9c53R453
